## Numpy Refrences


#### Install Numpy

In [2]:
#pip install numpy

#### Import Numpy

In [2]:
import numpy as np

### 1) Introduction

Numpy is python pacakage that provides multidimentional array object(or simply ndarray) and supports other mathmatical operation. It depends on an accelerated linear algebra library. It is used to vectorize the code. 



\begin{array}{l}
2 x+3 y=4 \ldots . .(1) \\
5 x-y=7 \ldots . .(2) \\
{\left[\begin{array}{rr}
2 & 3 \\
5 & -1
\end{array}\right]\left[\begin{array}{l}
x \\
y
\end{array}\right]=\left[\begin{array}{l}
4 \\
7
\end{array}\right]}
\end{array}

### Time Comparision: Vectorized vs Loop

In [6]:
arr = np.arange(10000) ## arr is list of number between 0 and 10000

Find sum regular loop

In [7]:
%%timeit
sum = 0
for x in arr:
    sum += x

1.55 ms ± 18.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Find sum vectorized numpy

In [8]:
%timeit  sum_vec = arr.sum()

7.05 µs ± 180 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Contents
#### 1. Initialize Numpy arrays
#### 2.  Changing nparrays without changing its elements
#### 3. Stacking nparrays
#### 3. Mathmatical Operation

---
<br />

### *1) Initialize Numpy arrays*

## Initialize

In [3]:
 # Initialize Directly
arr1 = np.array([1,2,3])
print(f'Initialize Directly: {arr1}')

#Check Type of a data structure
print(f'\nType of arr1: {type(arr1)}\n')


# Initalize through a variable
a_list = [1,2,4,5]
arr2 = np.array(a_list) 
print(f'Initalize through a variable: {arr2}')


# arr_3 is mutable
a_list2 = (1,2,3,4)
arr_3 = np.array(a_list2)
print(f'Last array: {arr_3}')

#Initialize nparray with data type
print(f'Initialize nparray with data type: {np.array([1,2,3],dtype=np.float)}') 

#Initialize nparray as float
print(f'Initialize nparray with Same type: {np.array([1.,2,3])}') 


#Initialize Matrix
np.array(np.mat('1 2; 3 4'))


Initialize Directly: [1 2 3]

Type of arr1: <class 'numpy.ndarray'>

Initalize through a variable: [1 2 4 5]
Last array: [1 2 3 4]
Initialize nparray with data type: [1. 2. 3.]
Initialize nparray with Same type: [1. 2. 3.]


array([[1, 2],
       [3, 4]])

Numpy doc to Generate Numbers from Different Distribution: https://numpy.org/doc/stable/reference/random/generator.html

## Generate

In [24]:
# Initialize a zeros nparray 
print(f'Initialize Zeros: \n{np.zeros((2,3))}\n') # Note the argument is shape so double brackets

# Initialize a Ones nparray 
print(f'Initialize Ones: \n{np.ones((2,3),dtype=int)}\n') # Note the argument is shape so double brackets

# Random int with range 2-10 and size (2,3)
print(f'Random int with range 2-10 and size (2,3):\n {np.random.randint(2,10,size=(2,3))}\n') 

# Initialize the Identity Matrix
print(f'Initialize Identity Matrix: \n{np.eye(3,3)}\n')

# Standard Normally distributed N(0,1) numbers of size (2,4,5)
print(f' Standard Normally distributed N(0,1) numbers of size (2,4,5):\n {np.random.randn(2,4,5)}')# Note no size as argument

Initialize Zeros: 
[[0. 0. 0.]
 [0. 0. 0.]]

Initialize Ones: 
[[1 1 1]
 [1 1 1]]

Random int with range 2-10 and size (2,3):
 [[4 9 9]
 [7 5 9]]

Initialize Identity Matrix: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 Standard Normally distributed N(0,1) numbers of size (2,4,5):
 [[[-0.64544824 -1.51304404 -1.37591274  0.00508362 -0.78618364]
  [-0.47789729  0.97713084  0.76675664  0.21784243  0.69166096]
  [ 0.84182729  0.62233288 -0.39658377  0.34376254 -0.65483739]
  [-0.9225994  -1.08886618 -1.67919231  1.04579266 -0.00798195]]

 [[-1.1738116  -1.27097883 -1.33562845  0.12335013  0.42654004]
  [ 1.53972398  0.07707966 -0.41494563  0.78594854 -0.368931  ]
  [ 1.43612124  0.79219879 -0.85597023 -1.30758438 -0.64913588]
  [ 1.0067202   0.31679251  0.67459116  2.1937734   0.40534861]]]


In [5]:
# Arrange a numpy array
print(f'Arrange: {np.arange(3,10)}')

#  evenly spaced numbers over a specified interval
print(f'LineSpace: {np.linspace(2.0, 3.0, num=5)}')

Arrange: [3 4 5 6 7 8 9]
LineSpace: [2.   2.25 2.5  2.75 3.  ]


 #### 2) *Changing nparrays without changing its elements*

### Shuffle and Permute

In [17]:

#Shuffling the nparray
np.random.shuffle(arr_a)
print(f'Shuffling arr_a: {arr_a}')

# Permutation of nparray
arr = np.arange(9).reshape((3, 3))
np.random.permutation(arr)
print(arr )

Shuffling arr_a: [ 6  5  1  9  7  0 10  4 11  3  8  2]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Transpose 

In [96]:
## Transpose 
print('Original nparray:\n',arr_b,arr_b.shape,'\nTranspose: \n',arr_b.T,arr_b.T.shape)

x = np.ones((1, 2, 3))
print(f'Shape of Original x: {x.shape}\t Shape of Transpose(1,0,2): {np.transpose(x, (1, 0, 2)).shape}')

Original nparray:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4) 
Transpose: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]] (4, 3)
Shape of Original x: (1, 2, 3)	 Shape of Transpose(1,0,2): (2, 1, 3)


#### Transpose(1,2,0)   =>  H W C to C H W    
---
#### np.transpose(npimg, (1, 2, 0)
---
#### Or torch image=>img = torch.transpose(img,2,0)

### Reshape

In [20]:
# Reshape the nparray
arr_a = np.arange(12)
print(f'arr_a before: {arr_a}')

arr_b = np.reshape(arr_a,(3,4))
print(f'Reshape the dimension of nparray:\n {arr_b}\n') # Note : dimension should match
print('Shape: ',arr_b.shape)

arr_a before: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshape the dimension of nparray:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Shape:  (3, 4)


### Flatten the nparray

In [27]:
print(f'Original Array: \n{arr_b} \n Flatten Array: \n{arr_b.flatten()}') ## arr_b.ravel

Original Array: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
 Flatten Array: 
[ 0  1  2  3  4  5  6  7  8  9 10 11]


### Squeeze 

In [34]:
# squeeze removes all the 1 dimension in all axes  
x = np.array([[[0], [1], [2]]])
print(f'Shape of X: {x.shape} \n Shape after Squeezed: {x.squeeze().shape}')

#Squeeze the Dimension specficed by axis
print(f'\nShape of X: {x.shape} \n Shape after Squeezed: {x.squeeze(axis=2).shape}') ## Squeezed axis 2

Shape of X: (1, 3, 1) 
 Shape after Squeezed: (3,)

Shape of X: (1, 3, 1) 
 Shape after Squeezed: (1, 3)


### Expand Dimension (2,) => (2,1)

In [46]:
x = np.array([1,2])
print(f'Original : {x.shape} \n Expanded : {np.expand_dims(x,axis=1).shape}')

## Short way to expand dim : x[:,None]
print(f'Original :{x.shape}\n Expanded(Short Way): {x[:,None].shape} \t {x[None,:].shape}')

Original : (2,) 
 Expanded : (2, 1)
Original :(2,)
 Expanded(Short Way): (2, 1) 	 (1, 2)


### 3. Stacking nparrays

### Axis argument  

#### Stackoverflow explanation of axis: https://stackoverflow.com/questions/17079279/how-is-axis-indexed-in-numpys-array

#### For 2d: 0 is down and 1 is right

In [57]:
x = np.random.randint(10,size=(2,3,4))
x

array([[[6, 8, 0, 5],
        [2, 1, 0, 8],
        [3, 5, 4, 1]],

       [[9, 4, 6, 0],
        [2, 4, 7, 9],
        [9, 5, 1, 3]]])

In [62]:
sumX = np.sum(x,axis=1)
print(sumX, '\tShape: ',sumX.shape)

[[11 14  4 14]
 [20 13 14 12]] 	Shape:  (2, 4)


if you do .sum(axis=n), for example, then dimension n is collapsed and deleted, with each value in the new matrix equal to the sum of the corresponding collapsed values. For example, if b has shape (5,6,7,8), and you do c = b.sum(axis=2), then axis 2 (dimension with size 7) is collapsed, and the result has shape (5,6,8). Furthermore, c[x,y,z] is equal to the sum of all elements b[x,y,:,z]

In [68]:
print(x[1,:,2], 'Equals\t',x[1,:,2].sum())

[6 7 1] Equals	 14


In [75]:
print(f'sumX[1,2]: {sumX[1,2]} \t \nequals: ')
print('x[1,0,2]=>',x[1,0,2],'+','x[1,1,2]=>',x[1,1,2],'+','x[1,2,2]=>',x[1,2,2],'=',x[1,:,2].sum())

sumX[1,2]: 14 	 
equals: 
x[1,0,2]=> 6 + x[1,1,2]=> 7 + x[1,2,2]=> 1 = 14


### Stacking: Concatenation , hstack,vstack,np.c_,np.r_ 

In [80]:

array1 = np.random.randint(3, size = (3, 4, 5))
array2 = np.random.randint(4, size = (3, 4, 5))

concatenated_array = np.concatenate((array1, array2), axis = 0)  # Axis = None flatten and joins 

print("Array 1 is \n", array1, "\n\n")
print("Array 2 is \n", array2, "\n\n")
print("Concatenated array is \n", concatenated_array, "\n\n", "and the dimensions of the concatenated array are: \n", concatenated_array.shape)

Array 1 is 
 [[[1 2 0 0 0]
  [0 0 1 2 0]
  [0 2 1 1 2]
  [2 1 2 1 0]]

 [[2 0 0 0 2]
  [2 1 1 0 1]
  [1 1 1 0 2]
  [0 0 1 1 2]]

 [[1 1 2 0 2]
  [0 1 1 0 0]
  [1 1 1 2 0]
  [1 0 1 0 0]]] 


Array 2 is 
 [[[3 3 0 1 1]
  [3 0 0 1 2]
  [3 1 2 1 0]
  [1 3 1 3 2]]

 [[2 3 1 0 1]
  [2 3 0 2 3]
  [3 1 3 2 3]
  [3 0 2 1 2]]

 [[3 3 3 3 1]
  [2 3 0 1 0]
  [2 1 1 1 2]
  [3 2 2 2 2]]] 


Concatenated array is 
 [[[1 2 0 0 0]
  [0 0 1 2 0]
  [0 2 1 1 2]
  [2 1 2 1 0]]

 [[2 0 0 0 2]
  [2 1 1 0 1]
  [1 1 1 0 2]
  [0 0 1 1 2]]

 [[1 1 2 0 2]
  [0 1 1 0 0]
  [1 1 1 2 0]
  [1 0 1 0 0]]

 [[3 3 0 1 1]
  [3 0 0 1 2]
  [3 1 2 1 0]
  [1 3 1 3 2]]

 [[2 3 1 0 1]
  [2 3 0 2 3]
  [3 1 3 2 3]
  [3 0 2 1 2]]

 [[3 3 3 3 1]
  [2 3 0 1 0]
  [2 1 1 1 2]
  [3 2 2 2 2]]] 

 and the dimensions of the concatenated array are: 
 (6, 4, 5)


#### Slicing 

##### Array : [ 1, 2, 3, 4, 5]
---
##### Index:    0, 1, 2, 3, 4
---
##### Index:   -5,-4,-3,-2,-1
---

In [93]:
array = np.random.randint(7, size=(3,4,5))
print('Original array:\n', array, '\n')

print('array[:,:,-2:]\n', array[:,:,-2:], '\n\n')

Original array:
 [[[4 4 0 6 3]
  [3 1 0 4 4]
  [6 6 0 4 2]
  [6 6 5 4 5]]

 [[5 3 4 0 4]
  [4 3 1 5 2]
  [4 5 0 4 3]
  [5 5 6 2 3]]

 [[1 0 4 0 6]
  [1 6 1 1 3]
  [5 3 4 0 6]
  [0 6 1 0 0]]] 

array[:,:,-2:]
 [[[6 3]
  [4 4]
  [4 2]
  [4 5]]

 [[0 4]
  [5 2]
  [4 3]
  [2 3]]

 [[0 6]
  [1 3]
  [0 6]
  [0 0]]] 




### 4. Mathmatical Operations

In [103]:
x = np.array([1.0,2,3,4])
print('Type of x',type(x))
print('Change to int x[0]: ',x[0].astype(int))

Type of x <class 'numpy.ndarray'>
Change to int x[0]:  1


np.sum() ,np.mean(),np.std(), np.max(),np.amax()

In [3]:
# Elementwise Maximum
np.maximum([2, 3, 4], [1, 5, 2])

array([2, 5, 4])

### np.where: apply elementwise condition

In [5]:
a = np.arange(10)
print(f'a: {a}\n Element cond : {np.where(a < 5, a, 10*a)}')

a: [0 1 2 3 4 5 6 7 8 9]
 Element cond : [ 0  1  2  3  4 50 60 70 80 90]


#### Element wise 

In [6]:

array1 = np.random.randint(5, size = (4, 5))
array2 = np.random.randint(6, size = ( 4, 5))

Hadmarad_product = array1 *  array2# OR np.multiply(array1, array2)
print("First array, array1 is \n:", array1, "\n")
print("Second array, array2 is \n:", array2, "\n")
print("The element wise product is \n", Hadmarad_product, "\n and the dimension of the resulting product is",  "\n\n",  Hadmarad_product.shape, "\n")

First array, array1 is 
: [[2 3 2 0 0]
 [1 1 2 2 2]
 [0 4 3 0 2]
 [2 2 1 1 0]] 

Second array, array2 is 
: [[1 1 0 2 5]
 [2 4 5 2 5]
 [4 2 0 4 0]
 [2 3 0 0 1]] 

The element wise product is 
 [[ 2  3  0  0  0]
 [ 2  4 10  4 10]
 [ 0  8  0  0  0]
 [ 4  6  0  0  0]] 
 and the dimension of the resulting product is 

 (4, 5) 



### Dot Product 

In [9]:
matrix1 = np.random.randint(4, size = (2, 3))
matrix2 = np.random.randint(4, size = (3, 2))

product = matrix1 @ matrix2 #matrix1.dot(matrix2) or np.matmul(A,B) or np.dot(A,B)
print(matrix1,matrix1.shape,'\n\n',matrix2,matrix2.shape,'\n\n',product, product.shape)

[[3 2 2]
 [0 1 0]] (2, 3) 

 [[2 1]
 [1 2]
 [2 2]] (3, 2) 

 [[12 11]
 [ 1  2]] (2, 2)


### Tensor Dot : https://stackoverflow.com/questions/41870228/understanding-tensordot

In [19]:
A = np.random.randint(2, size=(2, 3, 5))
B = np.random.randint(2, size=(3, 2, 4))

In [21]:
A

array([[[0, 0, 0, 0, 1],
        [0, 0, 1, 0, 1],
        [1, 1, 0, 0, 0]],

       [[1, 1, 1, 0, 1],
        [1, 1, 1, 1, 1],
        [0, 0, 1, 0, 0]]])

In [22]:
B

array([[[0, 0, 0, 1],
        [1, 0, 1, 0]],

       [[1, 0, 0, 0],
        [0, 1, 0, 1]],

       [[0, 1, 0, 0],
        [1, 0, 1, 0]]])

In [33]:
a = np.arange(60.).reshape(3,4,5)
b = np.arange(24.).reshape(4,3,2)
c = np.tensordot(a,b, axes=([1,0],[0,1]))
c.shape
print(a)
print(b)
print('\n',c,c.shape)





# A slower but equivalent way of computing the same...
d = np.zeros((5,2))
for i in range(5):
  for j in range(2):
    for k in range(3):
      for n in range(4):
        d[i,j] += a[k,n,i] * b[n,k,j]
c == d

[[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14.]
  [15. 16. 17. 18. 19.]]

 [[20. 21. 22. 23. 24.]
  [25. 26. 27. 28. 29.]
  [30. 31. 32. 33. 34.]
  [35. 36. 37. 38. 39.]]

 [[40. 41. 42. 43. 44.]
  [45. 46. 47. 48. 49.]
  [50. 51. 52. 53. 54.]
  [55. 56. 57. 58. 59.]]]
[[[ 0.  1.]
  [ 2.  3.]
  [ 4.  5.]]

 [[ 6.  7.]
  [ 8.  9.]
  [10. 11.]]

 [[12. 13.]
  [14. 15.]
  [16. 17.]]

 [[18. 19.]
  [20. 21.]
  [22. 23.]]]

 [[4400. 4730.]
 [4532. 4874.]
 [4664. 5018.]
 [4796. 5162.]
 [4928. 5306.]] (5, 2)


array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

## Equivalently:  Sumreduction of given axis
## d[i,j] = (a[: , : , i] * b[ : , : , j].T).sum()

In [48]:
(a[:,:,0] * b[:,:,0].T).sum()

4400.0

In [24]:
np.tensordot(A, B, axes=((0),(1)))

array([[[[1, 0, 1, 0],
         [0, 1, 0, 1],
         [1, 0, 1, 0]],

        [[1, 0, 1, 0],
         [0, 1, 0, 1],
         [1, 0, 1, 0]],

        [[1, 0, 1, 0],
         [0, 1, 0, 1],
         [1, 0, 1, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[1, 0, 1, 1],
         [1, 1, 0, 1],
         [1, 1, 1, 0]]],


       [[[1, 0, 1, 0],
         [0, 1, 0, 1],
         [1, 0, 1, 0]],

        [[1, 0, 1, 0],
         [0, 1, 0, 1],
         [1, 0, 1, 0]],

        [[1, 0, 1, 1],
         [1, 1, 0, 1],
         [1, 1, 1, 0]],

        [[1, 0, 1, 0],
         [0, 1, 0, 1],
         [1, 0, 1, 0]],

        [[1, 0, 1, 1],
         [1, 1, 0, 1],
         [1, 1, 1, 0]]],


       [[[0, 0, 0, 1],
         [1, 0, 0, 0],
         [0, 1, 0, 0]],

        [[0, 0, 0, 1],
         [1, 0, 0, 0],
         [0, 1, 0, 0]],

        [[1, 0, 1, 0],
         [0, 1, 0, 1],
         [1, 0, 1, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

  

The idea with tensordot is pretty simple - We input the arrays and the respective axes along which the sum-reductions are intended. The axes that take part in sum-reduction are removed in the output and all of the remaining axes from the input arrays are spread-out as different axes in the output keeping the order in which the input arrays are fed

In [9]: np.tensordot(A, B, axes=((0),(1))).shape
Out[9]: (6, 5, 3, 4)

A : (2, 6, 5) -> reduction of axis=0
B : (3, 2, 4) -> reduction of axis=1

Output : `(2, 6, 5)`, `(3, 2, 4)` ===(2 gone)==> `(6,5)` + `(3,4)` => `(6,5,3,4)`

In [12]: np.tensordot(A, B, axes=((0,1),(1,0))).shape
Out[12]: (5, 4)

A : (2, 3, 5) -> reduction of axis=(0,1)
B : (3, 2, 4) -> reduction of axis=(1,0)

Output : `(2, 3, 5)`, `(3, 2, 4)` ===(2,3 gone)==> `(5)` + `(4)` => `(5,4)`


$$
\begin{aligned}
u \otimes v 
&=  
\left(\begin{array}{cc} 
u_1
\left(\begin{array}{cc} 
v_1 & v_2 & v_3
\end{array}\right) 
\\
u_2
\left(\begin{array}{cc} 
v_1 & v_2 & v_3
\end{array}\right) 
\\
u_3
\left(\begin{array}{cc} 
v_1 & v_2 & v_3
\end{array}\right)
\end{array}\right) \\
&=  
\left(\begin{array}{cc} 
\left(\begin{array}{cc} 
u_1v_1 & u_1v_2 & u_1v_3
\end{array}\right) 
\\
\left(\begin{array}{cc} 
u_2v_1 & u_2v_2 & u_2v_3
\end{array}\right) 
\\
\left(\begin{array}{cc} 
u_3v_1 & u_3v_2 & u_3v_3
\end{array}\right)
\end{array}\right) \\
&=
\left(\begin{array}{cc} 
u_1v_1 & u_1v_2 & u_1v_3\\
u_2v_1 & u_2v_2 & u_2v_3\\
u_3v_1 & u_3v_2 & u_3v_3
\end{array}\right)
\end{aligned}
$$

Then the tensor array product of the vector arrays and the matrix array is calculated as follows:

$
\left(\begin{array}{cc} 
a_{0} \\ a_{1} \\ a_{2}
\end{array}\right)
\otimes
\left(\begin{array}{cc} 
b_{00} & b_{01} & b_{02} & b_{03}\\
b_{10} & b_{11} & b_{12} & b_{13}\\
b_{20} & b_{21} & b_{22} & b_{23}\\
b_{30} & b_{31} & b_{32} & b_{33}
\end{array}\right)
$


$
\begin{aligned}
\: \: \: \: \: \: \: \: &=
\left(\begin{array}{cc} 
a_{0}
\left(\begin{array}{cc} 
b_{00} & b_{01} & b_{02} & b_{03}\\
b_{10} & b_{11} & b_{12} & b_{13}\\
b_{20} & b_{21} & b_{22} & b_{23}\\
b_{30} & b_{31} & b_{32} & b_{33}
\end{array}\right) \\
a_{1}
\left(\begin{array}{cc} 
b_{00} & b_{01} & b_{02} & b_{03}\\
b_{10} & b_{11} & b_{12} & b_{13}\\
b_{20} & b_{21} & b_{22} & b_{23}\\
b_{30} & b_{31} & b_{32} & b_{33}
\end{array}\right) \\
a_{2}
\left(\begin{array}{cc} 
b_{00} & b_{01} & b_{02} & b_{03}\\
b_{10} & b_{11} & b_{12} & b_{13}\\
b_{20} & b_{21} & b_{22} & b_{23}\\
b_{30} & b_{31} & b_{32} & b_{33}
\end{array}\right) 
\end{array}\right) \\ &=
\left(\begin{array}{cc} 
a_{0}
\left(\begin{array}{cc} 
b_{00} & b_{01} & b_{02} & b_{03}\\
b_{10} & b_{11} & b_{12} & b_{13}\\
b_{20} & b_{21} & b_{22} & b_{23}\\
b_{30} & b_{31} & b_{32} & b_{33}
\end{array}\right) ,
a_{1}
\left(\begin{array}{cc} 
b_{00} & b_{01} & b_{02} & b_{03}\\
b_{10} & b_{11} & b_{12} & b_{13}\\
b_{20} & b_{21} & b_{22} & b_{23}\\
b_{30} & b_{31} & b_{32} & b_{33}
\end{array}\right) ,
a_{2}
\left(\begin{array}{cc} 
b_{00} & b_{01} & b_{02} & b_{03}\\
b_{10} & b_{11} & b_{12} & b_{13}\\
b_{20} & b_{21} & b_{22} & b_{23}\\
b_{30} & b_{31} & b_{32} & b_{33}
\end{array}\right) 
\end{array}\right) \\
&=
\left(\begin{array}{cc} 
\left(\begin{array}{cc} 
a_{0}b_{00} & a_{0}b_{01} & a_{0}b_{02} & a_{0}b_{03}\\
a_{0}b_{10} & a_{0}b_{11} & a_{0}b_{12} & a_{0}b_{13}\\
a_{0}b_{20} & a_{0}b_{21} & a_{0}b_{22} & a_{0}b_{23}\\
a_{0}b_{30} & a_{0}b_{31} & a_{0}b_{32} & a_{0}b_{33}
\end{array}\right)
,
\left(\begin{array}{cc} 
a_{1}b_{00} & a_{1}b_{01} & a_{1}b_{02} & a_{1}b_{03}\\
a_{1}b_{10} & a_{1}b_{11} & a_{1}b_{12} & a_{1}b_{13}\\
a_{1}b_{20} & a_{1}b_{21} & a_{1}b_{22} & a_{1}b_{23}\\
a_{1}b_{30} & a_{1}b_{31} & a_{1}b_{32} & a_{1}b_{33}
\end{array}\right)
,
\left(\begin{array}{cc} 
a_{2}b_{00} & a_{2}b_{01} & a_{2}b_{02} & a_{2}b_{03}\\
a_{2}b_{10} & a_{2}b_{11} & a_{2}b_{12} & a_{2}b_{13}\\
a_{2}b_{20} & a_{2}b_{21} & a_{2}b_{22} & a_{2}b_{23}\\
a_{2}b_{30} & a_{2}b_{31} & a_{2}b_{32} & a_{2}b_{33}
\end{array}\right)
\end{array}\right) \\
&=
\left(\begin{array}{cc} 
\left(\begin{array}{cc} 
\tau_{000} & \tau_{001} & \tau_{002} & \tau_{003}\\
\tau_{010} & \tau_{011} & \tau_{012} & \tau_{013}\\
\tau_{020} & \tau_{021} & \tau_{022} & \tau_{023}\\
\tau_{030} & \tau_{031} & \tau_{032} & \tau_{033}
\end{array}\right)
,
\left(\begin{array}{cc} 
\tau_{100} & \tau_{101} & \tau_{102} & \tau_{103}\\
\tau_{110} & \tau_{111} & \tau_{112} & \tau_{113}\\
\tau_{120} & \tau_{121} & \tau_{122} & \tau_{123}\\
\tau_{130} & \tau_{131} & \tau_{132} & \tau_{133}
\end{array}\right)
,
\left(\begin{array}{cc} 
\tau_{200} & \tau_{201} & \tau_{202} & \tau_{203}\\
\tau_{210} & \tau_{211} & \tau_{212} & \tau_{213}\\
\tau_{220} & \tau_{221} & \tau_{222} & \tau_{223}\\
\tau_{230} & \tau_{231} & \tau_{232} & \tau_{233}
\end{array}\right)
\end{array}\right)
\end{aligned}
$

This tensor array could be described as a 3D matrix array.`

In [15]:
A = np.random.randint(9, size=(3))
B = np.random.randint(9, size=(4,4))

print("A = \n", A)

print("B = \n", B)

print("A⨂B =\n", np.tensordot(A, B, axes=0))

A = 
 [0 6 2]
B = 
 [[1 1 3 6]
 [0 1 8 6]
 [1 1 5 7]
 [3 5 7 5]]
A⨂B =
 [[[ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]]

 [[ 6  6 18 36]
  [ 0  6 48 36]
  [ 6  6 30 42]
  [18 30 42 30]]

 [[ 2  2  6 12]
  [ 0  2 16 12]
  [ 2  2 10 14]
  [ 6 10 14 10]]]


### Padding

In [50]:
a1 = np.array([np.array([3, 1, 4, 1]), 
               np.array([5, 9, 2, 6]), 
               np.array([5, 3, 5, 8])])

a2 = np.array([np.array([9, 7, 9, 3]),
               np.array([2, 3, 8, 4])])

a3 = np.array([np.array([3, 3, 8, 3]), 
               np.array([2, 7, 9, 5]),
               np.array([0, 2, 8, 8]), 
               np.array([6, 2, 6, 4])])

A = np.array([a1, a2, a3],dtype=object)

print("A =\n", A.T)

A =
 [array([[3, 1, 4, 1],
       [5, 9, 2, 6],
       [5, 3, 5, 8]])
 array([[9, 7, 9, 3],
       [2, 3, 8, 4]])
 array([[3, 3, 8, 3],
       [2, 7, 9, 5],
       [0, 2, 8, 8],
       [6, 2, 6, 4]])]


Cutoff each array to make them equal size (First two or last two in this example)

In [52]:
A1 = [record[:2] for record in A]
A1 = np.array(A1)

print("A =\n", A)

print("A1 =\n", A1)

A =
 [array([[3, 1, 4, 1],
       [5, 9, 2, 6],
       [5, 3, 5, 8]])
 array([[9, 7, 9, 3],
       [2, 3, 8, 4]])
 array([[3, 3, 8, 3],
       [2, 7, 9, 5],
       [0, 2, 8, 8],
       [6, 2, 6, 4]])]
A1 =
 [[[3 1 4 1]
  [5 9 2 6]]

 [[9 7 9 3]
  [2 3 8 4]]

 [[3 3 8 3]
  [2 7 9 5]]]


Padd the bottom with zero 

pad_width{sequence, array_like, int}
---
Number of values padded to the edges of each axis. ((before_1, after_1), … (before_N, after_N)) unique pad widths for each axis. ((before, after),) yields same before and after pad for each axis. (pad,) or int is a shortcut for before = after = pad width for all axes.

In [53]:
pad_below1 = 4 - len(a1)
pad_below2 = 4 - len(a2)
pad_below3 = 4 - len(a3)

pad_above = 0
pad_left = 0
par_right = 0

n_add = [((pad_above, pad_below1), (pad_left, par_right)), 
         ((pad_above, pad_below2), (pad_left, par_right)), 
         ((pad_above, pad_below3), (pad_left, par_right))]

A3 = [np.pad(A[i], pad_width = n_add[i], mode = 'constant', constant_values = 0) for i in range(3)]
A3 = np.array(A3)

print("A =\n", A)

print("A3 =\n", A3)

A =
 [array([[3, 1, 4, 1],
       [5, 9, 2, 6],
       [5, 3, 5, 8]])
 array([[9, 7, 9, 3],
       [2, 3, 8, 4]])
 array([[3, 3, 8, 3],
       [2, 7, 9, 5],
       [0, 2, 8, 8],
       [6, 2, 6, 4]])]
A3 =
 [[[3 1 4 1]
  [5 9 2 6]
  [5 3 5 8]
  [0 0 0 0]]

 [[9 7 9 3]
  [2 3 8 4]
  [0 0 0 0]
  [0 0 0 0]]

 [[3 3 8 3]
  [2 7 9 5]
  [0 2 8 8]
  [6 2 6 4]]]


Padd above 

In [54]:
pad_above1 = 4 - len(a1)
pad_above2 = 4 - len(a2)
pad_above3 = 4 - len(a3)

pad_below = 0
pad_left = 0
par_right = 0

n_add = [((pad_above1, pad_below), (pad_left, par_right)), 
         ((pad_above2, pad_below), (pad_left, par_right)), 
         ((pad_above3, pad_below), (pad_left, par_right))]

A4 = [np.pad(A[i], pad_width = n_add[i], mode = 'constant', constant_values = 0) for i in range(3)]
A4 = np.array(A4)

print("A =\n", A)

print("A4 =\n", A4)

A =
 [array([[3, 1, 4, 1],
       [5, 9, 2, 6],
       [5, 3, 5, 8]])
 array([[9, 7, 9, 3],
       [2, 3, 8, 4]])
 array([[3, 3, 8, 3],
       [2, 7, 9, 5],
       [0, 2, 8, 8],
       [6, 2, 6, 4]])]
A4 =
 [[[0 0 0 0]
  [3 1 4 1]
  [5 9 2 6]
  [5 3 5 8]]

 [[0 0 0 0]
  [0 0 0 0]
  [9 7 9 3]
  [2 3 8 4]]

 [[3 3 8 3]
  [2 7 9 5]
  [0 2 8 8]
  [6 2 6 4]]]


### einsum

Blog Post:
For understanding : https://obilaniu6266h16.wordpress.com/2016/02/04/einstein-summation-in-numpy/

For Some quick Uses : https://rockt.github.io/2018/04/30/einsum

1. Vector inner product: "a,a->" (Assumes two vectors of same length)
2. Vector element-wise product: "a,a->a" (Assumes two vectors of same length)
3. Vector outer product: "a,b->ab" (Vectors not necessarily same length.)
4. Matrix transposition: "ab->ba"
5. Matrix diagonal: "ii->i"
5. Matrix trace: "ii->"
7. 1-D Sum: "a->"
8. 2-D Sum: "ab->"
9. 3-D Sum: "abc->"
10. Matrix inner product "ab,ab->" (If you pass twice the same argument, it becomes a matrix L2 norm)
11. Left-multiplication Matrix-Vector: "ab,b->a"
12. Right-multiplication Vector-Matrix: "a,ab->b"
13. Matrix Multiply: "ab,bc->ac"
14. Batch Matrix Multiply: "Yab,Ybc->Yac"
15. Quadratic form / Mahalanobis Distance: "a,ab,b->"
…

#### Under the hood

![caption](einsum.png)

#### Transpose  ||  x.T

In [73]:
x = np.random.randint(10,size=(2,3))
x_T = np.einsum('ij -> ji',x)
print(f'Original:\n {x} \nTranspose :\n{x_T}')

Original:
 [[1 3 1]
 [8 8 8]] 
Transpose :
[[1 8]
 [3 8]
 [1 8]]


#### Sum  || x.sum()

In [75]:
x = np.random.randint(10,size=(2,3))
x_sum = np.einsum('ij -> ',x)
print(f'Original:\n {x} \n Sum :\n{x_sum}')

Original:
 [[2 7 7]
 [2 7 3]] 
 Sum :
28


### Sum || x.sum(axis=0)

In [82]:
x = np.random.randint(10,size=(2,3))
x_sum0 = np.einsum('ij -> j',x)
print(f'Original:\n {x} \n Sum_0 :\n{x_sum0}')

Original:
 [[5 7 7]
 [3 3 3]] 
 Sum_0 :
[ 8 10 10]


### Sum || x.sum(axis=1)

In [83]:
x = np.random.randint(10,size=(2,3))
x_sum1 = np.einsum('ij -> i',x)
print(f'Original:\n {x} \n Sum_1 :\n{x_sum1}')

Original:
 [[0 9 5]
 [3 3 8]] 
 Sum_1 :
[14 14]


### Dot-Product || a@b

In [89]:
a = np.random.randint(10,size=(2,3))
b = np.random.randint(10,size=(3,4))
product = np.einsum('ij,jk->ik',a,b)
print(f'Original:\n {a} \n\n {b} \n product :\n{product}')

Original:
 [[6 0 8]
 [4 3 2]] 

 [[4 7 8 8]
 [5 4 8 2]
 [1 5 0 8]] 
 product :
[[ 32  82  48 112]
 [ 33  50  56  54]]


### Hadamard Product(ElementWise) || a*b

In [3]:
a = np.random.randint(10,size=(2,3))
b = np.random.randint(10,size=(2,3))
product = np.einsum('ij,ij->ij',a,b)
print(f'Original:\n {a} \n\n {b} \n product :\n{product}')

Original:
 [[9 9 0]
 [1 7 3]] 

 [[7 4 9]
 [7 5 9]] 
 product :
[[63 36  0]
 [ 7 35 27]]


### Batch Matrix Multiplication

In [12]:
a = np.random.randint(10,size=(3,4,5))
b = np.random.randint(10,size=(3,5,4))
product = np.einsum('ijk,ikl->ijl',a,b)
print(f'Original:\n {a} \n =========\n {b}\n  ++++++++++\nBatch Matrix Multiplication :\n{product}')

Original:
 [[[3 5 5 8 1]
  [1 8 3 8 5]
  [2 5 3 8 0]
  [2 7 9 7 3]]

 [[8 9 4 5 7]
  [2 6 0 5 2]
  [8 7 1 2 5]
  [2 9 1 0 9]]

 [[3 6 8 5 5]
  [5 3 0 7 2]
  [9 0 2 0 9]
  [7 1 7 4 0]]] 
 [[[8 2 9 5]
  [3 2 6 2]
  [5 8 6 5]
  [9 4 9 9]
  [8 9 9 1]]

 [[1 1 9 0]
  [9 6 8 5]
  [2 6 8 4]
  [1 5 5 0]
  [4 1 2 7]]

 [[2 9 2 6]
  [5 7 2 7]
  [6 0 4 2]
  [5 5 9 8]
  [8 6 6 0]]]
  ++++++++++
Batch Matrix Multiplication :
[[[144  97 168 123]
  [159 119 192 113]
  [118  70 138 107]
  [169 145 204 135]]

 [[130 118 215 110]
  [ 69  65  95  44]
  [ 95  71 156  74]
  [121  71 116 112]]

 [[149 124 125 116]
  [ 76 113  91 107]
  [102 135  80  58]
  [ 81  90  80  95]]]
